# Generated by Django 4.1.5 on 2023-01-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.TextField(choices=[('other', 'other'), ('pharmacy', 'pharmacy'), ('food', 'food')], max_length=50, verbose_name='category'),
        ),
    ]
